services:
  - type: web
    name: recipe-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-db
          property: connectionString

databases:
  - name: recipe-db
    engine: postgresql
    plan: free
